[package]
name = "tarnished"
version = "0.1.0"
authors = ["Trip Volpe <trip.volpe@gmail.com>"]

[dependencies]
sdl2 = "*"
sdl2_image = "*"
snes_spc = { git = "https://github.com/tripped/rust-snes_spc" }
