[package]
name = "tarnished"
version = "0.1.0"
authors = ["Trip Volpe <trip.volpe@gmail.com>"]

[dependencies]
sdl2 = "*"
sdl2_image = "*"
sdl2_ttf = "*"
snes_spc = { git = "https://github.com/tripped/rust-snes_spc" }
time = "0.1"
rustc-serialize = "*"
carboxyl = "*"
num = "*"
conv = "*"
